services:
  mysql:
    image: mysql:8
    container_name: mysql_v1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
    ports:
      - "3306:3306"
    volumes:
      - newMySqlVolume:/var/lib/mysql
    networks:
      - mynetwork

  web:
    image: vaishnaviputta/devops-project:${TAG:-latest}
    container_name: flask_app_v3
    env_file:
      - .env
    ports:
      - "8000:5000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root123}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mydb}
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  newMySqlVolume:
    driver: local

    
